# Site settings
title: Zixin Z. 

# #############################
#  SELF DEFINITION
baseurl: "/homepage"
url: "zixinzh.github.io"
# baseurl: "/ap"
# url: "https://kssim.github.io"
#  ############################
 
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Zixin Zhong (钟梓昕) # KyeongSeob Sim
  desc: Nice to meet you here.
  email: zixinDOTzhongATu.nus.edu # ksub0912@gmail.com 
  selfie: assets/img/zixin.jpg # profile.jpg

# social
social:
  email: true
#   behance:
#   bitbucket:
#   dribbble:
#   facebook: Test
#   flickr:
  google_scholar: https://scholar.google.com/citations?user=xy9V7MEAAAAJ&hl=en&oi=ao
  github: zixinzh # kssim
#   google_plus:
#   instagram:
#   keybase:
  linkedin: https://www.linkedin.com/in/zixin-zhong-5a7348209/ # https://www.linkedin.com/in/kssim/ 
#   pinterest:
#   reddit: 
#   soundcloud:
#   stack_exchange:
#   steam:
#   tumblr:
#   gitlab:
#   twitter: Test
#   vimeo:
#   wordpress:
#   youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png" 
